name: movies_mobile_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.0-prev3

  flutter:
    sdk: flutter
  flutter_hooks: ^0.16.0
  freezed_annotation: ^0.14.1
  hooks_riverpod: ^0.13.1+1
  json_annotation: ^4.0.1
  transparent_image: ^2.0.0

dev_dependencies:
  build_runner: ^1.10.11
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1
  json_serializable: ^4.0.0
  lint: ^1.5.3

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
